version: "2.0.0"
caliper:
  blockchain: fabric
  gateway:
    enabled: true
    discover: true

channels:
  - channelName: mychannel
    contracts:
      - id: patient
        version: '4.0'
    organizations:
      - Org1
      - Org2

organizations:
  - mspid: Org1MSP
    identities:
      certificates:
      - name: Admin
        admin: true
        clientPrivateKey:
          path: ../../../../hyperledger3/fabric-samples/test-network/organizations/peerOrganizations/org1.example.com/users/Admin@org1.example.com/msp/keystore/aa1e4ce18606839a45997c81fe67c740ea0833d991b25bce4dd17c3d3adc5a06_sk
        clientSignedCert:
          path: ../../../../hyperledger3/fabric-samples/test-network/organizations/peerOrganizations/org1.example.com/users/Admin@org1.example.com/msp/signcerts/cert.pem
    connectionProfile:
      path: ../../../../hyperledger3/fabric-samples/test-network/organizations/peerOrganizations/org1.example.com/connection-org1.json
      discover: true
    name: Org1

  - mspid: Org2MSP
    identities:
      certificates:
      - name: Admin
        admin: true
        clientPrivateKey:
          path: ../../../../hyperledger3/fabric-samples/test-network/organizations/peerOrganizations/org2.example.com/users/Admin@org2.example.com/msp/keystore/8dddc05897fba410f18146a2704323ab0362b520f121de481808bf651034d3c6_sk
        clientSignedCert:
          path: ../../../../hyperledger3/fabric-samples/test-network/organizations/peerOrganizations/org2.example.com/users/Admin@org2.example.com/msp/signcerts/cert.pem
    connectionProfile:
      path: ../../../../hyperledger3/fabric-samples/test-network/organizations/peerOrganizations/org2.example.com/connection-org2.json
      discover: true
    name: Org2
